[repositories_config]
    [repositories_config.postgres_config]
        host="localhost"
        port=5432
        login="wb_tech"
        password="wb_tech"
        db="L0"
        max_connections=100
        idle_timeout_sec=1200
        max_lifetime_sec=2
    [repositories_config.redis_config]
        host="localhost"
        port=6379
        login="wb_tech"
        password="wb_tech"
        db=0
        max_connections=100
        wait=2
        create=1    
    [repositories_config.local_config]
        path1="./raw_data_postgres.json"
        path2="./raw_data_redis.json"

