

[repositories_config]
    [repositories_config.postgres_config]
        host="localhost"
        port=5432
        login="wb_tech"
        password="wb_tech"
        db="L0"
        max_connections=100
        idle_timeout_sec=1200
        max_lifetime_sec=2
[data_saver_config]
    path="./raw_data.json"
